import type { Metadata } from "next";
import { Montez, Geist, Geist_Mono, Exo_2 } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import ThemeProvider from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const montez = Montez({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: "--font-montez", 
  display: "swap" 
});

const exo2 = Exo_2({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: "--font-exo2", 
  display: "swap" 
});

export const metadata: Metadata = {
  title: "Igotmessage App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#000000' },
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${montez.variable} ${exo2.variable}`}>
      <body className="flex items-center justify-center min-h-screen w-full">
        <ReduxProvider>
          <ThemeProvider>
          {children}
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
