import type { Metadata } from "next";
import { Montez, Geist, Geist_Mono, Exo_2 } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const montez = Montez({ subsets: ["latin"], weight: "400", variable: "--font-montez" });
const exo2 = Exo_2({ subsets: ["latin"], weight: "400", variable: "--font-exo2" });

export const metadata: Metadata = {
  title: " Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="color-scheme" content="light only" />
      </head>
      <body
        className={`flex items-center justify-center min-h-screen w-full ${geistSans.variable} ${geistMono.variable} ${montez.variable} ${exo2.variable} `}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}